name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with: 
        ref: main
    - name: Pull Docker image
      run: docker pull docker.elastic.co/elasticsearch/elasticsearch:7.17.22
      
    - name: save 
      run: docker save docker.elastic.co/elasticsearch/elasticsearch:7.17.22 -o image.tar
      
    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v3
      with:
        name: docker-image
        path: image.tar
